version: '3.1'
services:
  # use Docker secrets?
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1ubuntu9@"
      POSTGRES_USER: "avena"
      POSTGRES_DB: "avena"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/schema:/docker-entrypoint-initdb.d
  oada-upload:
    build:
      context: ./oada_upload
    restart: always
    env_file:
      oada_variables.env
    depends_on:
      - postgres
  adminer: # For dev ONLY
    image: adminer
    restart: always
    ports:
      - 8080:8080
  gps:
    image: abalmos/gps
    restart: always
    environment:
       GPSD_URL: "172.17.0.1:2947"
       DATABASE_URL: "postgres://avena:1ubuntu9@@postgres/avena"
  kafka:
    image: konradmalik/kafka-armhf
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: konradmalik/zookeeper-armhf
    ports:
      - "2181:2181"
  kafka-gps-log:
    image: wang701/kafka-gps-log:latest-armhf
    restart: always
    environment:
      kafka_topic: "${gps_topic}"
  kafka-can-log:
    image: wang701/kafka-can-log:latest-armhf
    restart: always
    network_mode: host
    extra_hosts:
      kafka: 127.0.0.1
    environment:
      can_dev: "${tra_interface}"
      kafka_topic: "${tra_interface}"
  engine-rpm-pub:
    image: wang701/engine-rpm-pub:latest-armhf
    restart: always
    environment:
      isoblue_id: "${isoblue_id}"
      kafka_topic: "${tra_interface}"
      mqtt_topic: "${mqtt_topic}"
      cloud_domain: "${avena_domain}"
      mqtt_port: "${mqtt_port}"
volumes:
  postgres:
