version: '3.1'
services:
  # use Docker secrets?
  postgres:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "avena"
      POSTGRES_DB: "avena"
      TIMESCALEDB_TELEMETRY: "off"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/schema:/docker-entrypoint-initdb.d
  oada-upload:
    build:
      context: ./oada_upload
    restart: always
    environment:
      isoblue_id: "ib999"
      oada_server_batchsize: "1000"
      oada_server_basepath: "/bookmarks/isoblue/device-index"
      oada_server_url: "server_url.example.com"
      oada_server_token: "abc"
      db_user: "avena"
      db_host: "postgres"
      db_database: "avena"
      db_password: "password"
      db_port: "5432"
    depends_on:
      - postgres
volumes:
  postgres:
