version: '3.1'
services:
  kafka:
    image: konradmalik/kafka-armhf
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: konradmalik/zookeeper-armhf
    ports:
      - "2181:2181"
  kafka-gs-log:
    image: wang701/kafka-gps-log:latest-armhf
    restart: always
    environment:
      kafka_topic: "${gps_topic}"