version: '3'
services:
  # docker run -it -v /var/run/dbus:/var/run/dbus --rm --name my-running-app my-python-app
  gps2tsdb:
    build:
      context: ./      
    restart: always
    environment:
      db_user: "avena"
      db_host: "postgres"
      db_database: "avena"
      db_password: "password"
      db_port: "5432"
#    depends_on:
#      - postgres
    volumes:
      - /var/run/dbus:/var/run/dbus:rw
      
#volumes:
#  dbus:
#    external:
#      name: "var/run/dbus:/var/run/dbus:rw"
